spring:
  jpa:
    database: MYSQL
  datasource:
    platform: mysql
    url: jdbc:mysql://119.3.52.175:3306/springhealth_user
    username: root
    password: 1qazxsw2#edc
    driver-class-name: com.mysql.jdbc.Driver